run:
  name: "workshop"
  disable_progressbar: true


countries: ["AT"]

foresight: "myopic"

scenario:
  simpl:
  - ""
  ll:
  - v1.5
  clusters:
  - 10
  opts:
  - ""
  sector_opts:
  - 10SEG-dist1-solar+c1.5
  planning_horizons:
  - 2020
  - 2025
  - 2030
  - 2035
  - 2040
  - 2045
  - 2050

electricity:
  extendable_carriers:
    Generator: [solar, onwind, OCGT]
  renewable_carriers: [solar, onwind, hydro]


solving:
  options:
    io_api: "direct"
  solver:
    name: "gurobi"
    # Alternative:
    # name: "highs"
    # options: "highs-default"

plotting:
  map:
    boundaries:
    color_geomap:
      ocean: white
      land: white
  projection:
    # See https://scitools.org.uk/cartopy/docs/latest/reference/projections.html for alternatives, for example:
    name: "LambertConformal"
    central_longitude: 10.
    central_latitude: 50.
    standard_parallels: [35, 65]
  eu_node_location:
    x: -5.5
    y: 46.
  costs_max: 50
  costs_threshold: 0.1
  energy_max: 300
  energy_min: -300
  energy_threshold: 2.
