name: pypsa-eur
channels:
  - bioconda
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.1
  - alsa-lib=1.2.3.2
  - amply=0.1.5
  - appdirs=1.4.4
  - asttokens=2.1.0
  - atlite=0.2.9
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blosc=1.21.1
  - boost-cpp=1.74.0
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cairo=1.16.0
  - cdsapi=0.5.1
  - certifi=2022.9.24
  - cfitsio=4.1.0
  - charset-normalizer=2.1.1
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.0
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.7
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coincbc=2.10.8
  - colorama=0.4.6
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - country_converter=0.7.7
  - curl=7.86.0
  - cycler=0.11.0
  - dask=2022.10.2
  - dask-core=2022.10.2
  - dbus=1.13.6
  - decorator=5.1.1
  - deprecation=2.1.0
  - descartes=1.1.0
  - distributed=2022.10.2
  - distro=1.6.0
  - entsoe-py=0.5.8
  - et_xmlfile=1.0.1
  - exceptiongroup=1.0.0
  - executing=1.2.0
  - expat=2.5.0
  - filelock=3.8.0
  - folium=0.13.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2022.10.0
  - geographiclib=1.52
  - geojson-rewind=1.0.2
  - geopandas=0.12.1
  - geopandas-base=0.12.1
  - geopy=2.2.0
  - geos=3.10.2
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.29
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.20.2
  - gstreamer=1.20.3
  - gurobi=9.5.2
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - icu=69.1
  - idna=3.4
  - importlib-metadata=5.0.0
  - importlib_resources=5.10.0
  - iniconfig=1.1.1
  - ipython=8.6.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.16
  - jsonschema=4.17.0
  - jupyter_core=4.11.2
  - kealib=1.4.15
  - keyutils=1.6.1
  - krb5=1.19.3
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=7.86.0
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgdal=3.5.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm13=13.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.38
  - libpq=14.2
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzip=1.9.2
  - libzlib=1.2.13
  - locket=1.0.0
  - lz4-c=1.9.3
  - lzo=2.10
  - mapclassify=2.4.3
  - matplotlib-base=3.6.0
  - matplotlib-inline=0.1.6
  - memory_profiler=0.60.0
  - msgpack-python=1.0.4
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbformat=5.7.0
  - ncurses=6.3
  - networkx=2.8.8
  - nomkl=1.0
  - nspr=4.32
  - nss=3.78
  - openjdk=11.0.1
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=21.3
  - parso=0.8.3
  - partd=1.3.0
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - plac=1.3.5
  - ply=3.11
  - poppler=22.04.0
  - poppler-data=0.4.11
  - postgresql=14.2
  - powerplantmatching=0.5.4
  - progressbar2=4.2.0
  - proj=9.0.0
  - prompt-toolkit=3.0.31
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycountry=20.7.3
  - pycparser=2.21
  - pygments=2.13.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pypsa=0.19.2
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyshp=2.3.1
  - pytables=3.7.0
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-utils=3.4.5
  - python_abi=3.10
  - pytz=2022.6
  - qt=5.12.9
  - ratelimiter=1.2.0
  - readline=8.1.2
  - requests=2.28.1
  - reretry=0.11.1
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - setuptools=65.5.0
  - setuptools-scm=7.0.5
  - setuptools_scm=7.0.5
  - six=1.16.0
  - smart_open=6.2.0
  - smmap=3.0.5
  - snakemake-minimal=7.18.1
  - snappy=1.1.9
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.4
  - stack_data=0.6.0
  - stopit=1.1.2
  - tabulate=0.9.0
  - tblib=1.7.0
  - threadpoolctl=3.1.0
  - tiledb=2.9.5
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - toposort=1.7
  - tqdm=4.64.1
  - traitlets=5.5.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzcode=2022e
  - tzdata=2022f
  - unidecode=1.3.6
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xarray=2022.10.0
  - xerces-c=3.2.3
  - xlrd=2.0.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zict=2.2.0
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - bokeh==2.4.3
    - bottleneck==1.3.5
    - brotlipy==0.7.0
    - cartopy==0.20.2
    - cffi==1.15.1
    - cftime==1.6.2
    - click==8.1.3
    - contourpy==1.0.6
    - countrycode==0.2
    - cryptography==38.0.3
    - cytoolz==0.12.0
    - datrie==0.8.2
    - docutils==0.19
    - dpath==2.0.6
    - fiona==1.8.21
    - fonttools==4.38.0
    - gdal==3.5.0
    - jedi==0.18.1
    - jupyter-core==4.11.2
    - kiwisolver==1.4.4
    - lxml==4.8.0
    - lz4==4.0.2
    - markupsafe==2.1.1
    - matplotlib==3.6.0
    - msgpack==1.0.4
    - netcdf4==1.6.0
    - numexpr==2.8.3
    - numpy==1.23.4
    - openpyxl==3.0.10
    - pandas==1.5.1
    - pillow==9.2.0
    - pluggy==1.0.0
    - psutil==5.9.3
    - pulp==2.7.0
    - pyomo==6.4.2
    - pyproj==3.3.1
    - pyqt5==5.12.3
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pyrsistent==0.19.1
    - pysocks==1.7.1
    - pytest==7.2.0
    - pyyaml==6.0
    - rasterio==1.2.10
    - rtree==1.0.1
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - shapely==1.8.2
    - statsmodels==0.0.0
    - tables==3.7.0
    - tabula-py==2.5.0
    - tornado==6.1
    - tsam==2.1.0
    - unicodedata2==15.0.0
    - vresutils==0.3.1
    - wrapt==1.14.1
    - yte==1.5.1
